In [1]:
# Consider the below code to answer further questions:

import numpy as np

list_ = [ '1', '2', '3', '4', '5']

array_list = np.array(object = list_)
print(array_list)

['1' '2' '3' '4' '5']


**Q1.** Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [3]:
# Yes, there is a difference in the data types of the list_ and array_list variables.
# The elements in the list_ are of type string, while the elements in the array_list are of type numpy string.

print("Data type of list_:", type(list_[0]))
print("Data type of array_list:", type(array_list[0]))


Data type of list_: <class 'str'>
Data type of array_list: <class 'numpy.str_'>


**Q2.** Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [4]:
# Print data types for each element in list_
print("Data types in list_:")
for element in list_:
    print(type(element))

# Print data types for each element in array_list
print("\nData types in array_list:")
for element in array_list:
    print(type(element))

Data types in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


**Q3.** Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [6]:
# Yes, with the given change where we explicitly set the data type of the NumPy array array_list to int,
# there will be a difference in the data types.
# The elements in list_ are of type string, while the elements in array_list will be of type integer.

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data types for each element in list_
print("Data types in list_:")
for element in list_:
    print(type(element))

# Print data types for each element in array_list
print("\nData types in array_list:")
for element in array_list:
    print(type(element))

Data types in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [7]:
# Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
print(num_list)

num_array = np.array(object = num_list)
print('\n')
print(num_list)

[[1, 2, 3], [4, 5, 6]]


[[1, 2, 3], [4, 5, 6]]


**Q4.** Write a code to find the following characteristics of variable, num_array:

(i) shape

(ii) size


In [12]:
print("Shape of num_array is:", num_array.shape)
print("Size of num_array is:",num_array.size)

Shape of num_array is: (2, 3)
Size of num_array is: 6


**Q5.** Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [13]:
zeros_array = np.zeros((3, 3))

print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


**Q6.** Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [14]:
identity_matrix = np.eye(5)

print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
